#!/bin/bash

cwd=$(pwd)
home_dir=home
udev_rules_dir=etc/udev/rules.d
nm_pre_up_dir=etc/NetworkManager/dispatcher.d/pre-up.d

for file in $cwd/$home_dir/*; do
    if [[ `basename $file` == 'config' ]]; then
        for file in $cwd/$home_dir/config/*; do
            ln -snfv $file ~/.config/`basename $file`
        done
    else
        ln -snfv $file ~/.`basename $file`
    fi
done

for file in $cwd/$udev_rules_dir/*; do
    sudo ln -snfv $file /$udev_rules_dir
done

for file in $cwd/$nm_pre_up_dir/*; do
    sudo ln -snfv $file /$nm_pre_up_dir
done
